syntax on

set showcmd
" blue      default  desert   evening   koehler  murphy  peachpuff  ron    slate  zellner
" darkblue  delek    elflord  industry  morning  pablo   README.txt     shine  torte javascript
colorscheme koehler
set nu
set tabstop=4
set shiftwidth=4
set autoindent
set nowrap
set incsearch
set autoindent
set cindent
set smartindent

" code folding
set foldmethod=indent   
set foldnestmax=10
set nofoldenable
set foldlevel=2

so ~/.vim/plugin.vim
" au VimEnter *  NERDTree

"YouCompleteMe
" Start autocompletion after 2 chars
let g:ycm_min_num_of_chars_for_completion = 2
let g:ycm_min_num_identifier_candidate_chars = 2
let g:ycm_enable_diagnostic_highlighting = 0
nmap gd :YcmCompleter GoToDefinition<CR>

"make lightline work in single screen
set laststatus=2

"set up for othree/javascript-libraries-syntax.vim
let g:used_javascript_libs = ''

" add by simba
nmap <tab> :s/^/\t<CR>
nmap <S-tab> :s/^\t/<CR>
nmap <F8> :TagbarToggle<CR>
nmap <F2> i#!/bin/bash<CR>
nmap <F3> :r! cat<CR>
nmap <F5> :NERDTreeToggle<CR>
nmap <S-@> :%s/  /\t/g<CR>
nmap <C-b> :!bash<CR>

au BufReadPost *.ejs set syntax=html

" instant markdown d
let g:instant_markdown_slow = 1
let g:instant_markdown_mathjax = 1

" vim-autoformat
nmap f :Autoformat<CR>

" Align GitHub-flavored Markdown tables
au FileType markdown vmap <Leader><Bslash> :EasyAlign*<Bar><Enter>


" preservim/nerdcommenter
filetype plugin on
" Add spaces after comment delimiters by default
let g:NERDSpaceDelims = 1
" Use compact syntax for prettified multi-line comments
let g:NERDCompactSexyComs = 1
" Align line-wise comment delimiters flush left instead of following code indentation
let g:NERDDefaultAlign = 'left'
" Set a language to use its alternate delimiters by default
let g:NERDAltDelims_java = 1
" Add your own custom formats or override the defaults
let g:NERDCustomDelimiters = { 'c': { 'left': '/**','right': '*/' } }
" Allow commenting and inverting empty lines (useful when commenting a region)
let g:NERDCommentEmptyLines = 1
" Enable trimming of trailing whitespace when uncommenting
let g:NERDTrimTrailingWhitespace = 1
" Enable NERDCommenterToggle to check all selected lines is commented or not 
let g:NERDToggleCheckAllLines = 1
