# preload = /home/simba-arch/Pictures/wallpapers/1.png
# preload = /home/simba-arch/Pictures/wallpapers/2.png
# preload = /home/simba-arch/Pictures/wallpapers/3.png
preload = /home/simba-arch/Pictures/wallpapers/4.png
# preload = /home/simba-arch/Pictures/wallpapers/5.png
# preload = /home/simba-arch/Pictures/wallpapers/6.png
wallpaper = , /home/simba-arch/Pictures/wallpapers/4.png
