---@type LazySpec
return {
  "AstroNvim/astrocommunity",
  -- { import = "astrocommunity.markdown-and-latex.markdown-preview-nvim" }, -- no longer maintained, switch to selimacerbas/markdown-preview.nvim
  { import = "astrocommunity.completion.copilot-lua-cmp" },
  { import = "astrocommunity.completion.cmp-tmux" },
  { import = "astrocommunity.pack.lua" },
  { import = "astrocommunity.pack.typst" },
  { import = "astrocommunity.pack.astro" },
  { import = "astrocommunity.pack.bash" },
  { import = "astrocommunity.pack.docker" },
  { import = "astrocommunity.pack.go" },
  { import = "astrocommunity.pack.html-css" },
  { import = "astrocommunity.pack.json" },
  { import = "astrocommunity.pack.markdown" },
  { import = "astrocommunity.pack.python.base" },
  { import = "astrocommunity.pack.python.basedpyright" },
  { import = "astrocommunity.pack.python.ruff" },
  { import = "astrocommunity.pack.toml" },
  { import = "astrocommunity.pack.yaml" },
  { import = "astrocommunity.pack.typescript" },
  { import = "astrocommunity.pack.tailwindcss" },
  { import = "astrocommunity.pack.cpp" },
  { import = "astrocommunity.pack.dart" },
  { import = "astrocommunity.pack.templ" },
  { import = "astrocommunity.pack.rust" },
  { import = "astrocommunity.pack.mdx" },
  -- { import = "astrocommunity.pack.zig" },
  { import = "astrocommunity.pack.svelte" },
  { import = "astrocommunity.pack.ansible" },
  { import = "astrocommunity.scrolling.nvim-scrollbar" },
  { import = "astrocommunity.terminal-integration.vim-tmux-yank" },
  { import = "astrocommunity.media.codesnap-nvim" },
  { import = "astrocommunity.editing-support.undotree" },

  -- { import = "astrocommunity.pack.xml" },
  -- { import = "astrocommunity.pack.java" },
  -- { import = "astrocommunity.pack.php" },
  -- { import = "astrocommunity.media.image-nvim" },
  -- { import = "astrocommunity/editing-support/multicursors-nvim" },
  -- { import = "astrocommunity/editing-support/comment-box-nvim" },
}
